### ISSUE TITLE
SK6812 mini-e on 3.3V

### ISSUE THREAD

**Issue by JF-Morin** [db-ok/SofleChocWireless#8]
Hi! I was wondering how you manage to make the LEDs work on 3.3V? On the datasheet, their working voltage is 3.7V to 5.5V. Nice project BTW :)

**Comment by db-ok** [comment]
Thanks! 

It may not be within the stated voltage range of the LEDs, but I have these same LEDs running on multiple boards, including some that were not originally designed for wireless usage, and haven't had issues. The nice!nano VCC output voltage has no trouble driving them. They do reduce your battery life significantly, so you have to be ok with using bigger batteries than most ZMK keyboards use, otherwise your runtime will suffer (it will still suffer because of the LEDs anyway, but that is inevitable). Check out this tool to estimate battery life running ZMK if you want to see how the LEDs affect it: https://zmk.dev/power-profiler

**Comment by JF-Morin** [comment]
Thx for the response :)
